services:
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile

  db:
    image: postgres
    container_name: StockTrackDb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - StockTrackDb_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
    StockTrackDb_data: